from typing import *

class ArArchive:
    def extract(self) -> None: ...

class DebFile:
    def __init__(self, file: object) -> None: ...
    control: TarFile
    data: TarFile

class TarMember:
    def isblk(self) -> bool: ...
    def ischr(self) -> bool: ...
    def isdev(self) -> bool: ...
    def isdir(self) -> bool: ...
    def isfifo(self) -> bool: ...
    def isfile(self) -> bool: ...
    def islnk(self) -> bool: ...
    def isreg(self) -> bool: ...
    def issym(self) -> bool: ...

    gid: int
    linkname: str
    major: int
    minor: int
    mode: int
    mtime: int
    name: str
    size: int
    uid: int

class TarFile:
    def extractall(self, rootdir: str = '') -> None: ...
    def extractdata(self, member: str) -> bytes: ...
    def go(self, callback: Callable[[TarMember, bytes], None], member : str = '') -> None: ...
