# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Jun  6 21:15:23 2022
# ------------------------------------------------

package:
  name: entrez-direct
  version: '16.2'
source:
  sha256: 42124ac5aa9aed2bb399b064ad4dfe418b9facb6f61eef95ac7e92e7cc410dd3
  url: https://raw.githubusercontent.com/biostars/conda-ready-entrez-direct/main/dist/edirect-16.2.20211103.tar.gz
build:
  number: '1'
  string: he881be0_1
requirements:
  build:
    - _go_select 2.2.0 nocgo
    - go 1.17.6 he1b62bb_0
    - go-nocgo_linux-64 1.17.6 h5bec462_1
  run:
    - wget
test:
  commands:
    - efetch --help
    - epost --help
    - efilter --help
    - einfo --help
    - esearch --help
    - elink --help
    - esummary --help
    - xtract -version
about:
  home: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/16.2.20211103/README
  license: PUBLIC DOMAIN
  summary: Entrez Direct (EDirect) is an advanced method for accessing the NCBI's
    set of interconnected databases (publication, sequence, structure, gene, variation,
    expression, etc.) from a UNIX terminal window. Functions take search terms from
    command-line arguments. Individual operations are combined to build multi-step
    queries. Record retrieval and formatting normally complete the process.
extra:
  container:
    extended-base: true
  copy_test_source_files: true
  final: true
