# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun May 22 20:52:16 2022
# ------------------------------------------------

package:
  name: importlib-metadata
  version: 4.11.4
source:
  sha256: 5d26852efe48c0a32b0509ffbc583fda1a2266545a78d104a6f4aff3db17d700
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-4.11.4.tar.gz
build:
  number: '0'
  string: py39hf3d152e_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.5.18.1 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h166bdaf_1014
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.3 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.1.1 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.9.12 h2660328_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 62.3.2 py39hf3d152e_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - setuptools_scm 6.4.2 hd8ed1ab_0
    - sqlite 3.38.5 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h166bdaf_1014
  run:
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
    - zipp >=0.5
about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - marcelotrevisani
    - nehaljwani
    - nicoddemus
