#! /bin/sh
set -e

# Automatically added by dh_icons/13.3.4ubuntu2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/Adwaita
	fi
fi
# End automatically added section


update-alternatives --install /usr/share/icons/default/index.theme \
        x-cursor-theme /usr/share/icons/Adwaita/cursor.theme 90
