#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	rmdir /var/run/dbus || true

	rm -f /var/lib/dbus/machine-id
	rmdir /var/lib/dbus || true

	LAUNCHER=/usr/lib/dbus-1.0/dbus-daemon-launch-helper

	if dpkg-statoverride --list "$LAUNCHER" >/dev/null 2>&1 ; then
		dpkg-statoverride --remove "$LAUNCHER"
	fi
fi

# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d dbus remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/session.conf 1.10.0-4\~ dbus -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.conf 1.10.0-4\~ dbus -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
