#! /bin/sh

# Automatically added by dh_installdebconf/13.6ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


set -e

case "$1" in
  purge)
    if [ "${DPKG_MAINTSCRIPT_PACKAGE_REFCOUNT:-1}" = 1 ]; then
      if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/papersize
      fi
      rm -f /etc/papersize
    fi
  ;;
esac
exit 0

