#!/bin/sh
#
# prerm script for the Debian GNU/Linux r-base-core package
# This version written by Dirk Eddelbuettel <edd@debian.org>   

set -e

# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/bash_completion.d/R /usr/share/bash-completion/completions/R -- "$@"
# End automatically added section

    
case "$1" in
    remove|purge)
	# edd 03 Apr 2003  cf Section 10.1.2 of Debian Policy
	rmdir /usr/local/lib/R/site-library 2>/dev/null || true
	rmdir /usr/local/lib/R/ 2>/dev/null || true
	# edd 10 May 2009  cf Section 10.7.3 of Debian Policy
	#                  and well as #527618
	rm /etc/R/Renviron 2>/dev/null || true
	ucf --purge /etc/R/Renviron
	ucfr --purge r-base-core /etc/R/Renviron
    ;;
    upgrade|abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
    ;;
esac
