#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dhcp/dhclient-exit-hooks.d/timesyncd 245.4-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/systemd/timesyncd.conf 245.4-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dhcp/dhclient-enter-hooks.d/resolved 246-2ubuntu1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pam.d/systemd-user 246.6-3\~ -- "$@"
# End automatically added section
