#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/lib/systemd/timesync/
    ;;
esac

# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'systemd-timesyncd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'systemd-timesyncd.service' >/dev/null || true
		deb-systemd-helper unmask 'systemd-timesyncd.service' >/dev/null || true
	fi
fi
# End automatically added section

