#!/bin/sh
set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule

  db_purge
fi

# Automatically added by dh_installinit/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/x11-common" ]; then
		update-rc.d x11-common defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native x11-common $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
