#!/bin/sh
'''exec' /opt/conda/conda-bld/focus_1640785337967/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from focus_app.focus import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
