# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Mar 26 23:36:12 2021
# ------------------------------------------------

package:
  name: kmer-jellyfish
  version: 2.3.0
source:
  sha256: e195b7cf7ba42a90e5e112c0ed27894cd7ac864476dc5fb45ab169f5b930ea5a
  url: https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz
build:
  number: '2'
  string: h7d875b9_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - autoconf 2.69 pl5320h36c2ea0_10
    - automake 1.16.2 pl5320ha770c72_3
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - ca-certificates 2020.12.5 ha878542_0
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gdbm 1.18 h0a1914f_2
    - gettext 0.19.8.1 h0b5b191_1005
    - gmp 6.2.1 h58526e2_0
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtool 2.4.6 h58526e2_1007
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - perl 5.32.0 h36c2ea0_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - readline 8.0 he28a2e2_2
    - ruby 2.7.2 he592edb_3
    - sysroot_linux-64 2.12 h77966d4_13
    - yaggo 1.5.10 0
    - yaml 0.2.5 h516909a_0
    - zlib 1.2.11 h516909a_1010
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
  run:
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
test:
  commands:
    - jellyfish --version 2>&1 > /dev/null
about:
  dev_url: https://github.com/gmarcais/Jellyfish
  home: http://www.genome.umd.edu/jellyfish.html
  license: GPL-3.0
  license_family: GPL
  summary: Jellyfish is a tool for fast, memory-efficient counting of k-mers in DNA.
    A k-mer is a substring of length k, and counting the occurrences of all such substrings
    is a central step in many analyses of DNA sequence
extra:
  copy_test_source_files: true
  final: true
  identifiers:
    - biotools:jellyfish
    - doi:10.1093/bioinformatics/btr011
